# Model Training
#### 1.1 Import Data and Required Packages

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier, 
    BaggingClassifier, 
    GradientBoostingClassifier, 
    AdaBoostClassifier
    )
from sklearn.metrics import (accuracy_score, 
                             precision_score, 
                             recall_score, 
                             f1_score, 
                             classification_report
                             )

In [3]:
df = pd.read_csv("G:/Graduation Project/Crop_Recommendation_System/notebook/data/Crop_Recommendation.csv")
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

#### Preparing X and Y variables

In [4]:
X = df.drop(columns=['label'],axis=1)
y = df['label']

In [5]:
X.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340

In [6]:
y.head()

0    rice
1    rice
2    rice
3    rice
4    rice
Name: label, dtype: object

In [7]:
# Encoded y (df['label'])
le = LabelEncoder()
y_encoded = le.fit_transform(y)

y_encoded

array([22, 22, 22, ...,  4,  4,  4])

In [8]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [9]:
# Create scaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#### Create an Evaluate Function to give all metrics after model Training

In [10]:
def evaluate_classification_model(true, predicted):
    accuracy = accuracy_score(true, predicted)
    precision = precision_score(true, predicted, average='weighted', zero_division=0)
    recall = recall_score(true, predicted, average='weighted', zero_division=0)
    f1 = f1_score(true, predicted, average='weighted', zero_division=0)
    return accuracy, precision, recall, f1

In [11]:
models = {
    'LogisticRegression': LogisticRegression(),
    'GaussianNB':GaussianNB(),
    'SVC':SVC(),
    'KNeighborsClassifier':KNeighborsClassifier(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'ExtraTreeClassifier':ExtraTreeClassifier(),
    'RandomForestClassifier':RandomForestClassifier(),
    'BaggingClassifier':BaggingClassifier(),
    'GradientBoostingClassifier':GradientBoostingClassifier(),
    'AdaBoostClassifier':AdaBoostClassifier()
}

model_list = []
accuracy_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_accur , model_train_prec, model_train_recall, model_train_f1 = evaluate_classification_model(y_train, y_train_pred)
    model_test_accur , model_test_prec, model_test_recall, model_test_f1 = evaluate_classification_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(model_train_accur))
    print("- F1 Score: {:.4f}".format(model_train_f1))
    print("- Precision: {:.4f}".format(model_train_prec))
    print("- Recall: {:.4f}".format(model_train_recall))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Accuracy: {:.4f}".format(model_test_accur))
    print("- F1 Score: {:.4f}".format(model_test_f1))
    print("- Precision: {:.4f}".format(model_test_prec))
    print("- Recall: {:.4f}".format(model_test_recall))

    accuracy_list.append(model_test_accur)
    
    print('='*35)
    print('\n')

LogisticRegression
Model performance for Training set
- Accuracy: 0.9764
- F1 Score: 0.9763
- Precision: 0.9768
- Recall: 0.9764
----------------------------------
Model performance for Test set
- Accuracy: 0.9615
- F1 Score: 0.9616
- Precision: 0.9629
- Recall: 0.9615
===================================


GaussianNB
Model performance for Training set
- Accuracy: 0.9909
- F1 Score: 0.9909
- Precision: 0.9912
- Recall: 0.9909
----------------------------------
Model performance for Test set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
===================================


SVC
Model performance for Training set
- Accuracy: 0.9885
- F1 Score: 0.9884
- Precision: 0.9894
- Recall: 0.9885
----------------------------------
Model performance for Test set
- Accuracy: 0.9827
- F1 Score: 0.9827
- Precision: 0.9842
- Recall: 0.9827
===================================


KNeighborsClassifier
Model performance for Training set
- Accuracy: 0.9894
- F1 Score: 0.9894
- Precision: 0.9899
- Recall: 0.9894
----------------------------------
Model performance for Test set
- Accuracy: 0.9750
- F1 Score: 0.9750
- Precision: 0.9773
- Recall: 0.9750
===================================


DecisionTreeClassifier
Model performance for Training set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9827
- F1 Score: 0.9825
- Precision: 0.9835
- Recall: 0.9827
===================================


ExtraTreeClassifier
Model performance for Training set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9058
- F1 Score: 0.9052
- Precision: 0.9091
- Recall: 0.9058
===================================


RandomForestClassifier
Model performance for Training set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9981
- F1 Score: 0.9981
- Precision: 0.9982
- Recall: 0.9981
===================================


BaggingClassifier
Model performance for Training set
- Accuracy: 0.9995
- F1 Score: 0.9995
- Precision: 0.9995
- Recall: 0.9995
----------------------------------
Model performance for Test set
- Accuracy: 0.9846
- F1 Score: 0.9848
- Precision: 0.9865
- Recall: 0.9846
===================================


GradientBoostingClassifier
Model performance for Training set
- Accuracy: 1.0000
- F1 Score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.9827
- F1 Score: 0.9827
- Precision: 0.9832
- Recall: 0.9827
===================================


AdaBoostClassifier
Model performance for Training set
- Accuracy: 0.1140
- F1 Score: 0.0495
- Precision: 0.0441
- Recall: 0.1140
----------------------------------
Model performance for Test set
- Accuracy: 0.1212
- F1 Score: 0.0549
- Precision: 0.0492
- Recall: 0.1212
===================================

#### View Results

In [12]:
results_df = pd.DataFrame({
    'Model': model_list,
    'Test Accuracy': accuracy_list
}).sort_values(by='Test Accuracy', ascending=False)

print("--- Model Comparison ---")
results_df

--- Model Comparison ---

                        Model  Test Accuracy
1                  GaussianNB       1.000000
6      RandomForestClassifier       0.998077
7           BaggingClassifier       0.984615
8  GradientBoostingClassifier       0.982692
2                         SVC       0.982692
4      DecisionTreeClassifier       0.982692
3        KNeighborsClassifier       0.975000
0          LogisticRegression       0.961538
5         ExtraTreeClassifier       0.905769
9          AdaBoostClassifier       0.121154

**insight**
- GaussianNB is the winner!!

In [16]:
Gauss = GaussianNB()
Gauss = Gauss.fit(X_train, y_train)
y_pred = Gauss.predict(X_test)
score = accuracy_score(y_test, y_pred)*100
print(f" Accuracy of the model is {score:.2f}%")

 Accuracy of the model is 100.00%

#### Difference between Actual and Predicted Values

In [14]:
pred_df = pd.DataFrame({
    'Actual Value':y_test,
    'Predicted Value':y_pred,
    'Difference':y_test-y_pred
    })
pred_df

     Actual Value  Predicted Value  Difference
0               0                0           0
1              12               12           0
2               3                3           0
3               6                6           0
4               0                0           0
..            ...              ...         ...
515            18               18           0
516            12               12           0
517            20               20           0
518            22               22           0
519            25               25           0

[520 rows x 3 columns]

#### Testing our Model

In [20]:
feature_names = X.columns.tolist() 

def recommendation(N,P,K,temperature,humidity,ph,rainfall):

    features_list = [[N,P,K,temperature,humidity,ph,rainfall]]
    features_df = pd.DataFrame(features_list, columns=feature_names)

    scaler_features = scaler.transform(features_df)

    prediction_code = Gauss.predict(scaler_features)
    prediction_name = le.inverse_transform(prediction_code)
    
    return prediction_name[0]


N=90
P= 42
K= 43
temperature= 20.879744
humidity=82.002744
ph=6.502985
rainfall= 202.935536

prediction = recommendation(N,P,K,temperature,humidity,ph,rainfall)

print(f"The recommended crop is: {prediction}")

The recommended crop is: rice